version: '3.8'

services:
  neko-image-gallery:
    # Uncomment this section to build image from source code
    build:
      context: .
      dockerfile: Dockerfile
    image: tuhinmallick/neko-image-gallery:latest-cuda12.1
    ports:
      - "8000:8000"
    volumes:
      - "./static:/opt/NekoImageGallery/static"
    env_file:
      - ./config/.env  # This references the .env file for environment variables
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

networks:
  default:
    name: neko-image-gallery
